spring.application.name=SistemaCaja
# Configuracion de conexion MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bd_sistema_caja?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=2222
# Configuracion Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT (modulo de autenticacion)
jwt.secret=claveSecretaCibertecSistemaCajaProyectoAcademico2026CambiarEnProduccion
jwt.expiration=86400000